version: '3.8'

services:
  mariadb:
    image: mariadb:11.2
    container_name: codifica-guali-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: codifica_guali
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - codifica-network
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: codifica-guali-app
    restart: always
    ports:
      - "8090:8080"
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_NAME: codifica_guali
      DB_USER: root
      DB_PASSWORD: root
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - codifica-network

volumes:
  mariadb_data:
    driver: local

networks:
  codifica-network:
    driver: bridge